### PR TITLE
Allows for the MITM/Authentication level to be adjusted by exposing the setting

### PR DESCRIPTION
**Pull request by brofloyd**
Allows for the MITM/Authentication level to be adjusted by exposing the setting

### CODE REVIEW

**Comment by peterfoot** [comment]
I'm getting some more information on the various values in this enumeration because in the Bluetooth spec MITM is a single bit - if we only need required/not required we don't need the whole enumeration in the public API and it might even make sense to expose as a bool.

**Comment by brofloyd** [comment]
I think one of the reasons I liked the enumeration, is because you can specify bonding as well. I've been working with a number of devices, and I've noticed that each one has different requirements for communication.

**Comment by peterfoot** [comment]
Sorry this has hit a roadblock but I'm still awaiting feedback from Microsoft. Essentially some of the enum entries appear to refer to other types of pairing e.g. initiated by the remote device and I'm not sure all are used by BluetoothAuthenticateDeviceEx. Because of this I don't want to expose a Win32 in the public API if it is not relevant to all platforms where it could be a simple boolean option, or be on by default if that is the behaviour on other platforms (including WinRT as eventually the Win32 version will be obsolete).

**Comment by brofloyd** [comment]
Hi Peter,
I was wondering if you had any news about exposing this setting. I've been doing work with various bluetooth devices and found that different levels of protection and bonding are required. For instance, on one device, I am only able to create a successful pair when I change the Bluetooth Authentication Requirement to MITMProtectionRequiredBonding. However, other devices use no MITM/ no bonding. So having a singular authentication requirement doesn't fit all BT classic pairing needs. If you would like me to update the PR, I can do that as well.

**Comment by peterfoot** [comment]
Superceded by #301

**Pull request closed without merging**
