### PR TITLE
Added a SetMtu method for change the default mtu size 20 for Android

### PR DESCRIPTION
**Pull request by polipo**
The Mtu cannot be set on PlatformInit() method it doesnt work.
I have added a public SetMtu(value) method, it request Mtu size only for Android platform

### CODE REVIEW

**Comment by peterfoot** [comment]
Thanks for submitting this. I think there is potential to still allow the Mtu to be requested as required but then the request is made internally after the connection state changed callback (as you've said the call after the connect method will fail as connection is not yet established). If set when already connected then the request can be made directly. The reason for setting a new default value is the Android default of 20 bytes is very small and completely out of step with the default values on other platforms.

**Comment by Asejere** [comment]
Ok

**Comment by polipo** [comment]
Where can be fixed! is a bug it doesnt work please can be fixed or add a method Gatt.SetMtu(ushort value)

**Comment by peterfoot** [comment]
Sorry, I didn't get around to this push request due to illness. The intention is to add a RequestMtu method which can be called at any time to set a preferred value. On Android this will not be physically set until the connection is established. Changes in the Mtu will be reflected back in the public Mtu property.
Remember that for all of these wrapper types you can access the underlying native object for the RemoteGattServer in device specific code by casting to an Android.Bluetooth.BluetoothGatt as all these types have implicit operators.

**Comment by polipo** [comment]
Perfect I didn't remember to cast it to RemoteGattServer and it works

**Pull request merged**
